import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import Link from 'next/link'

export default function Home({ post }) {
  const router = useRouter()

  const data = [
    { name: "Aziz1", id: 1 },
    { name: "Aziz2", id: 2 },
    { name: "Aziz3", id: 3 },
  ]

  const user = {
    name: "Shahriyor",
    age: 23,
    color: "red"
  }

  const JSON = [
    { name: "Rahmiddin", age: 12, address: "Tashkent", id: 1 },
    { name: "Aziza", age: 13, address: "Samarqand", id: 2 },
    { name: "Nodira", age: 14, address: "Tashkent", id: 3 },
    { name: "Muyassar", age: 15, address: "Samarqand", id: 4 },
    { name: "Gulom", age: 16, address: "Tashkent", id: 5 },
    { name: "Suhrob", age: 17, address: "Samarqand", id: 6 },
    { name: "Gayrat", age: 18, address: "Tashkent", id: 7 },
    { name: "Nurmuhammad", age: 19, address: "Samarqand", id: 8 },
  ]





  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <style jsx global>{`
        body {
          margin: 0;
          padding: 0;
          font-size: 18px;
          font-weight: 400;
          line-height: 1.8;
          color: #333;
          font-family: sans-serif;
        }
        a {
          margin: 10px;
          font-size: 20px;
          font-weight: 900;

        }
      `}</style>



      {
        JSON.map(item => {
          return (
            <Link href={{ pathname: `/demo/hello`, query: item }}>
              <a>{item.name}</a>
            </Link>
          )
        })
      }







      {
        data.map((item, index) => {
          return (
            <Link href={{
              pathname: `/demo/${item.id}`,
              query: {
                name: item.name
              }
            }} >
              <a style={{color: "red"}}>user {index += 1}</a>
            </Link>
          )
        })
      }



    </div >
  )
}
